keys:
  - &mark age1sapnea5rpnhv8j3v6rrhsjj3tlh9e67hf5u8vl4yrrel965txyfs6yhrps
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *mark
  - path_regex: secrets/mark/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *mark