# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, inputs, ... }:

{
  services.openvpn = {
    servers = {
      radboud = {
        config = ''
          client
          proto tcp
          dev tun
          ca /etc/ssl/certs/ca-certificates.crt
          remote-cert-tls server
          auth-user-pass
          cipher AES-256-CBC
          verify-x509-name openvpn.science.ru.nl name
          auth SHA256
          comp-lzo
          verb 3
          remote openvpn.science.ru.nl 443

          allow-compression yes
          compat-mode 2.4.7
        '';
      };
    };

    # config = ''
    #   compat-mode 2.4.7
    # '';
  };
}
